import { Container } from "@cloudflare/containers";
import { env } from "cloudflare:workers";

export class MediShareApiContainer extends Container {
  defaultPort = 8080;
  sleepAfter = "10m";
  enableInternet = true;

  envVars = {
    NODE_ENV: env.NODE_ENV,
    APP_ENV: env.APP_ENV,
    PORT: env.PORT,
    JWT_EXPIRES_IN: env.JWT_EXPIRES_IN,
    RENDER_JOBS_VIA_CLOUDFLARE_QUEUE: env.RENDER_JOBS_VIA_CLOUDFLARE_QUEUE,
    MONGODB_URI: env.MONGODB_URI,
    JWT_SECRET: env.JWT_SECRET,
    CLIENT_URL: env.CLIENT_URL,
    CLOUDFLARE_ACCOUNT_ID: env.CLOUDFLARE_ACCOUNT_ID,
    CLOUDFLARE_ACCESS_KEY_ID: env.CLOUDFLARE_ACCESS_KEY_ID,
    CLOUDFLARE_SECRET_ACCESS_KEY: env.CLOUDFLARE_SECRET_ACCESS_KEY,
    CLOUDFLARE_BUCKET_NAME: env.CLOUDFLARE_BUCKET_NAME,
    CLOUDFLARE_PUBLIC_DOMAIN: env.CLOUDFLARE_PUBLIC_DOMAIN,
    CLOUDFLARE_FOLDER_PREFIX: env.CLOUDFLARE_FOLDER_PREFIX,
  };
}
